site_name: PhD Thesis - Exploration and Application of Choreography Principles in Industrial Automation

extra_css:
  - stylesheets/extra.css

theme: 
  name: material
  icon: 
    logo: material/school
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: custom
    accent: custom
  copyright: Copyright &copy; 2025 Andreas Stutz 
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.sections
    - navigation.path
nav:
  - PhD Thesis: index.md
  - Research Hypothesis: methodology\research-hypothesis.md
  - Design Science Research: methodology/design-science-research.md
  - Publications: publications/publications.md
  - Design Science Artifacts: 
    - Framework: artifacts\automation-service-choreography-framework.md
    - Choreographed System Architecture: artifacts\choreography-enabled-system-architecture.md
    - Active Participant: artifacts\active-choreography-participant.md
    - Passive Participant: artifacts\passive-choreography-participant.md
    - External Lead: artifacts\external-lead.md
    - Artficats: artifacts\configurable-logic.md
    - Configurable Communication: artifacts\configurable-communication.md
    - Configuralbe Communication OPC UA CS: artifacts\configurable-communication-opcuacs.md
    - Configuralbe Communication OPC UA PS: artifacts\configurable-communication-opcuaps.md
    - Configuralbe Communication OPC UA FX: artifacts\configurable-communication-opcuafx.md
  - Implementations: 
    - SIMATIC TIA Portal: implementations\tia-portal\tia-portal-overview.md
    - BECKHOFF TwinCat: implementations\twincat\twincat-overview.md 
  - License: license.md

plugins:


markdown_extensions:
  - toc:
      baselevel: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg